[workspace]
resolver = "2"
members = ["crates/*", "src-tauri"]
default-members = ["crates/*", "src-tauri"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Jamie"]
repository = "https://github.com/jamiedarville/BiblioChad"
rust-version = "1.80"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
strip = true
panic = "unwind"
